---
Name: inbox
---

HudhaifaS\Inbox\Model\InboxMessage:
  extensions:
    - HudhaifaS\DOM\Extension\DataObject_MemberExtension
    
SilverStripe\Security\Member:
  extensions:
    - HudhaifaS\Inbox\Extension\MemberInboxExtension
