---
Name: inbox
After: dataobject-manager
---

HudhaifaS\Inbox\Model\InboxMessage:
  extensions:
    - HudhaifaS\Extension\MemberOwnershipExtension
    
SilverStripe\Security\Member:
  extensions:
    - HudhaifaS\Inbox\Extension\MemberInboxExtension
