---
Name: inbox
---

InboxMessage:
  extensions:
    - HudhaifaS\DOM\Extension\DataObject_MemberExtension
    
SilverStripe\Security\Member:
  extensions:
    - HudhaifaS\Inbox\Extension\MemberInboxExtension
