---
Name: inbox
---

InboxMessage:
  extensions:
    - HudhaifaS\DOM\Extensions\DataObject_MemberExtension
    
SilverStripe\Security\Member:
  extensions:
    - HudhaifaS\Inbox\MemberInboxExtension
